import type { Listing } from "@/store/listings";

/**
 * Seed listings for Hyderabad — used for MVP dev/demo
 * These will be replaced by real database queries
 */
export const SEED_LISTINGS: Listing[] = [
  {
    id: "1",
    latitude: 17.4401,
    longitude: 78.3489,
    price: 8500000,
    propertyType: "apartment",
    listingType: "sale",
    listerType: "owner",
    bedrooms: 2,
    bathrooms: 2,
    builtUpArea: 1150,
    address: "Gachibowli",
    city: "Hyderabad",
  },
  {
    id: "2",
    latitude: 17.4486,
    longitude: 78.3908,
    price: 15000000,
    propertyType: "apartment",
    listingType: "sale",
    listerType: "broker",
    bedrooms: 3,
    bathrooms: 3,
    builtUpArea: 1850,
    address: "Jubilee Hills",
    city: "Hyderabad",
  },
  {
    id: "3",
    latitude: 17.4156,
    longitude: 78.4347,
    price: 4500000,
    propertyType: "apartment",
    listingType: "sale",
    listerType: "owner",
    bedrooms: 2,
    bathrooms: 1,
    builtUpArea: 950,
    address: "Mehdipatnam",
    city: "Hyderabad",
  },
  {
    id: "4",
    latitude: 17.4948,
    longitude: 78.3996,
    price: 22000000,
    propertyType: "villa",
    listingType: "sale",
    listerType: "developer",
    bedrooms: 4,
    bathrooms: 4,
    builtUpArea: 3200,
    address: "Banjara Hills",
    city: "Hyderabad",
  },
  {
    id: "5",
    latitude: 17.3616,
    longitude: 78.4747,
    price: 3200000,
    propertyType: "apartment",
    listingType: "sale",
    listerType: "owner",
    bedrooms: 2,
    bathrooms: 1,
    builtUpArea: 850,
    address: "Dilsukhnagar",
    city: "Hyderabad",
  },
  {
    id: "6",
    latitude: 17.4375,
    longitude: 78.4482,
    price: 6500000,
    propertyType: "apartment",
    listingType: "sale",
    listerType: "broker",
    bedrooms: 3,
    bathrooms: 2,
    builtUpArea: 1400,
    address: "Himayatnagar",
    city: "Hyderabad",
  },
  {
    id: "7",
    latitude: 17.4637,
    longitude: 78.3565,
    price: 12000000,
    propertyType: "house",
    listingType: "sale",
    listerType: "owner",
    bedrooms: 3,
    bathrooms: 3,
    builtUpArea: 2200,
    address: "Kondapur",
    city: "Hyderabad",
  },
  {
    id: "8",
    latitude: 17.4483,
    longitude: 78.3091,
    price: 7500000,
    propertyType: "apartment",
    listingType: "sale",
    listerType: "developer",
    bedrooms: 2,
    bathrooms: 2,
    builtUpArea: 1250,
    address: "Manikonda",
    city: "Hyderabad",
  },
  {
    id: "9",
    latitude: 17.3950,
    longitude: 78.5500,
    price: 4000000,
    propertyType: "plot",
    listingType: "sale",
    listerType: "owner",
    plotArea: 1500,
    address: "Uppal",
    city: "Hyderabad",
  },
  {
    id: "10",
    latitude: 17.5114,
    longitude: 78.3411,
    price: 18000000,
    propertyType: "villa",
    listingType: "sale",
    listerType: "developer",
    bedrooms: 4,
    bathrooms: 5,
    builtUpArea: 4000,
    address: "Nallagandla",
    city: "Hyderabad",
  },
  {
    id: "11",
    latitude: 17.3850,
    longitude: 78.4867,
    price: 25000,
    propertyType: "apartment",
    listingType: "rent",
    listerType: "owner",
    bedrooms: 2,
    bathrooms: 1,
    builtUpArea: 900,
    address: "Malakpet",
    city: "Hyderabad",
  },
  {
    id: "12",
    latitude: 17.4260,
    longitude: 78.3340,
    price: 45000,
    propertyType: "apartment",
    listingType: "rent",
    listerType: "broker",
    bedrooms: 3,
    bathrooms: 2,
    builtUpArea: 1500,
    address: "Financial District",
    city: "Hyderabad",
  },
  {
    id: "13",
    latitude: 17.4969,
    longitude: 78.3925,
    price: 55000000,
    propertyType: "commercial",
    listingType: "sale",
    listerType: "developer",
    builtUpArea: 5000,
    address: "Begumpet",
    city: "Hyderabad",
  },
  {
    id: "14",
    latitude: 17.4474,
    longitude: 78.3762,
    price: 9800000,
    propertyType: "apartment",
    listingType: "sale",
    listerType: "owner",
    bedrooms: 3,
    bathrooms: 2,
    builtUpArea: 1600,
    address: "Madhapur",
    city: "Hyderabad",
  },
  {
    id: "15",
    latitude: 17.3688,
    longitude: 78.5247,
    price: 3500000,
    propertyType: "house",
    listingType: "sale",
    listerType: "owner",
    bedrooms: 2,
    bathrooms: 2,
    builtUpArea: 1100,
    address: "LB Nagar",
    city: "Hyderabad",
  },
];
